spring:
  cloud:
    gateway:
      routes[0]:
        id: microservice-product
        predicates: Path=/api/v1/products/**
        filters: StripPrefix=3
        uri: lb://microservice-product
      routes[1]:
        id: microservice-client
        predicates: Path=/api/v1/clients/**
        filters: StripPrefix=3
        uri: lb://microservice-client
      routes[2]:
        id: microservice-transaction
        predicates: Path=/api/v1/transactions/**
        filters: StripPrefix=3
        uri: lb://microservice-transaction
      routes[3]:
        id: microservice-account
        predicates: Path=/api/v1/accounts/**
        filters: StripPrefix=3
        uri: lb://microservice-account
      routes[4]:
          id: microservice-product-client
          predicates: Path=/api/v1/productsClients/**
          filters: StripPrefix=3
          uri: lb://microservice-product-client
      routes[5]:
            id: microservice-card
            predicates: Path=/api/v1/cards/**
            filters: StripPrefix=3
            uri: lb://microservice-card
      routes[6]:
            id: microservice-yanki-association
            predicates: Path=/api/v1/yanki/association/**
            filters: StripPrefix=4
            uri: lb://microservice-yanki-association
      routes[7]:
            id: microservice-bootcoin-buy
            predicates: Path=/api/v1/bootcoin/buy/**
            filters: StripPrefix=4
            uri: lb://microservice-bootcoin-buy
      routes[8]:
            id: microservice-bootcoin-sales
            predicates: Path=/api/v1/bootcoin/sales/**
            filters: StripPrefix=4
            uri: lb://microservice-bootcoin-sales
      routes[9]:
            id: microservice-yanki
            predicates: Path=/api/v1/yankis/**
            filters: StripPrefix=3
            uri: lb://microservice-yanki
      discovery:
        locator:
          enabled: 'true'
    loadbalancer:
      ribbon:
        enabled: 'false'
  application:
    name: microservice-gateway

server:
  port: '8090'

eureka:
  instance:
    hostname: localhost
  client:
    fetch-registry: 'true'
    register-with-eureka: 'true'
    service-url:
      defaultZone: http://localhost:8761/eureka