spring:
  cloud:
    gateway:
      routes[0]:
        id: microservice-product
        uri: lb://microservice-product
        predicates: Path=/api/**
        filters: StripPrefix=1
      discovery:
        locator:
          enabled: 'true'
    loadbalancer:
      ribbon:
        enabled: 'false'
  application:
    name: microservice-gateway

server:
  port: '8090'

eureka:
  instance:
    hostname: localhost
  client:
    fetch-registry: 'true'
    register-with-eureka: 'true'
    service-url:
      defaultZone: http://localhost:8761/eureka
